version: '2'

services:
    web:
        image: nginx:latest
        container_name: barber-nginx
        ports:
            - "8084:80"
        volumes:
            - ./code:/code
            - ./logs:/var/log/nginx/
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        build: 
          context: ./
          dockerfile: laravel.docker
        container_name: siof-laravel
        working_dir: /code
        volumes:
            - ./code:/code
        environment:
            - APP_LOG_LEVEL=debug
        links:
            - barber_db
    barber_db:
        image: mariadb
        restart: always
        ports:
            - 3309:3306
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: siof
            MYSQL_USER: siof
            MYSQL_PASSWORD: 123456